language: node_js

node_js:
  - 0.10
  - 0.12

sudo: false

env:
  - NODE_ENV=test

install:
  - npm install
  - npm shrinkwrap
  - nsp audit-shrinkwrap

before_script:
  - export PATH=$PATH:$PWD/node_modules/.bin

script: npm run cover

after_success: ./tasks/travis_after_success.sh

